frontend/src/App.css, frontend/src/App.tsx, frontend/src/Routine.ts
=> Feature/2 構成要求グループ得点

frontend/package-lock.json, frontend/package.json, frontend/src/App.css, frontend/src/App.tsx, frontend/src/components/EventButtons.tsx, frontend/src/components/HeaderIcons.tsx
=> [Add]HeaderをSP対応

frontend/src/components/EventButtons.tsx
=> [Fix]種目選択ボタンの矢印の方向が逆だった

frontend/src/App.tsx
=> [Modify]演技構成モードで種目変更時にエンプティメッセージを表示するように変更

frontend/src/App.css, frontend/src/App.tsx
=> [Modify]演技構成表の技名を改行できるように変更

frontend/src/App.css
=> [Modify]難度マークの背景色を元に戻した

frontend/src/App.css, frontend/src/App.tsx, frontend/src/Routine.ts, frontend/src/Type.ts, frontend/src/components/AppliedRules.tsx, frontend/src/components/EventButtons.tsx
=> Feature/14 関連ルールの表示

frontend/src/App.css, frontend/src/App.tsx, frontend/src/Routine.ts, frontend/src/Type.ts, frontend/src/components/AppliedRules.tsx
=> Feature/4 床ダブル系必須

frontend/src/App.tsx
=> [Add]PC→SPモード変更時にSideモードのままにならないように変更

frontend/src/App.css, frontend/src/components/atoms/RoutineTableElement.tsx, frontend/src/components/molecules/RoutineRules.tsx, frontend/src/components/molecules/RoutineTable.tsx
=> [Modify]関連ルールにセクションを導入

frontend/src/components/molecules/ElementsGroup.tsx
=> [Fix]ElementTileにkeyプロパティを追加

frontend/src/components/molecules/RoutineTable.tsx
=> [Fix]RoutineTableElementにkeyプロパティを追加

frontend/src/App.css, frontend/src/App.tsx, frontend/src/components/molecules/RoutineTable.tsx, frontend/src/components/organisms/Routine.tsx
=> [Modify]演技構成エンプティメッセージの追加 & 演技構成表のスタイル変更

frontend/src/App.tsx, frontend/src/utilities/RoutineUtil.ts
=> Feature/56 6種目保存機能&local storageに永続化

frontend/src/App.tsx
=> [Add]selectEventとselectGroupをlocalStorageに保存

frontend/src/components/molecules/RoutineRules.tsx, frontend/src/components/molecules/RoutineTable.tsx, frontend/src/utilities/RoutineUtil.ts
=> [Modify]ND計算関数からダブル系不足を床のみに変更

frontend/src/App.css, frontend/src/components/molecules/RoutineRules.tsx, frontend/src/components/molecules/RoutineTable.tsx
=> [Add]演技構成リセットボタンの実装

frontend/src/components/molecules/RoutineRules.tsx, frontend/src/utilities/RoutineUtil.ts
=> [Fix]routineが空だった場合のエラーを解消

frontend/src/components/molecules/RoutineRules.tsx, frontend/src/utilities/RoutineSRUtil.ts
=> [Modify]力技制限1のsummary-label表示条件を変更

frontend/src/components/molecules/RoutineRules.tsx
=> [Fix]力技制限1のコードリストが存在しない場合をガード

frontend/src/App.css, frontend/src/components/molecules/RoutineRules.tsx
=> [Fix]つり輪の力技制限1の選択中技表示を修正

frontend/src/App.css, frontend/src/App.tsx
=> [Fix]難度表の右端が見切れる問題を解消

frontend/src/components/molecules/RoutineRules.tsx
=> [Fix]「逆も可」の横幅を1rem追加

frontend/src/App.css, frontend/src/components/atoms/ElementsTile.tsx, frontend/src/components/molecules/ElementsGroup.tsx, frontend/src/components/organisms/Elements.tsx
=> [Add]拡大縮小ボタンの実装

frontend/src/App.css
=> [Modify]ズームボタンの色を修正

frontend/src/App.css
=> [Modify]SPモードのズームアイコンサイズ変更

frontend/src/App.css, frontend/src/components/organisms/Header.tsx
=> [Add]アイコンをHeaderに追加&Headerのリファクタリング

frontend/src/App.css
=> [Fix]アイコン位置微調整

frontend/src/App.css, frontend/src/App.tsx, frontend/src/components/molecules/HeaderEventButtons.tsx, frontend/src/components/organisms/Header.tsx
=> Feature/134 pc種目アイコンに選択中技数を表示する

frontend/src/App.css, frontend/src/components/molecules/HeaderEventButtons.tsx
=> [Modify]event-dropdownのスタイルを修正

frontend/src/components/molecules/HeaderEventButtons.tsx
=> [Fix]技数=0の種目のスタイルを非表示に修正

frontend/src/App.css, frontend/src/components/atoms/StyledBadge.tsx, frontend/src/components/molecules/HeaderEventButtons.tsx, frontend/src/components/molecules/HeaderIcons.tsx
=> [Modify]技数をバッチスタイルで右上に表示

frontend/src/App.css, frontend/src/App.tsx, frontend/src/components/molecules/RoutineTable.tsx, frontend/src/components/organisms/Routine.tsx
=> [Add]全種目リセット機能実装

frontend/src/App.css, frontend/src/components/atoms/StyledBadge.tsx, frontend/src/components/molecules/HeaderEventButtons.tsx, frontend/src/components/molecules/HeaderIcons.tsx, frontend/src/components/organisms/Header.tsx
=> Feature/138 全種目リセット機能

frontend/src/App.css
=> [Modify]種目変更ボタンのスタイル変更

frontend/src/App.css, frontend/src/components/molecules/RoutineRules.tsx
=> [Modify]Dスコアルールの説明をインタラクティブ化

frontend/src/App.css, frontend/src/components/atoms/ElementsTile.tsx, frontend/src/components/molecules/RoutineTable.tsx, frontend/src/components/pages/Hint.tsx
=> Feature/146 モードレス

frontend/src/App.css
=> [Fix]Hintの位置を変更

frontend/src/App.tsx, frontend/src/components/organisms/Elements.tsx
=> [Modify]sp/pcの初期表示倍率を設定

frontend/src/App.tsx
=> [Fix]エンプティメッセージを開発中から取得中に変更

frontend/src/App.css, frontend/src/App.tsx
=> [Modify]LPスタイル修正&routineOpenのlocalStorage保存を削除&PCモードのroutineOpenの初期値を1に

frontend/src/App.css, frontend/src/App.tsx, frontend/src/components/atoms/ElementsTile.tsx, frontend/src/components/pages/Hint.tsx
=> [Modify]鍵アイコン&チェックアイコンの追加&HintにDスコア表示追加

frontend/src/components/pages/Hint.tsx
=> [Fix]デバッグ用記述を戻し忘れてた

frontend/src/utilities/RoutineUtil.ts
=> [Fix]合計Dスコアを修正

frontend/src/components/molecules/RoutineRules.tsx, frontend/src/components/organisms/Hint.tsx, frontend/src/utilities/RoutineSRUtil.ts
=> [Fix]つり輪力技制限2に正常に飛ぶようにHint周りを修正
